### ISSUE TITLE
gn gen out/test

### ISSUE THREAD

**Issue by unknownbug** [mbbill/Chromium_Base#1]
linux下，gn args out/mybuild  报错
Waiting for editor on "/home/wf/github/Chromium_Base/src/out/list/args.gn"...
Generating files...
ERROR at //build/config/BUILDCONFIG.gn:127:15: Reading a variable defined in the same declare_args() call.

If you need to set the value of one arg based on another, put
them in two separate declare_args() calls, one after the other.

  is_debug = !is_official_build
              ^---------------

**Comment by mbbill** [comment]
The project is not yet ported to Linux. You may find the [cobalt](https://cobalt.googlesource.com/cobalt/+/COBALT_6/src)  project useful if you need it for Linux.
