### ISSUE TITLE
windows下运行./build.bat

### ISSUE THREAD

**Issue by unknownbug** [mbbill/Chromium_Base#2]
注意: 包含文件:  C:\Program Files (x86)\Windows Kits\8.1\include\um\shellscalingapi.h
注意: 包含文件:  C:\Program Files (x86)\Windows Kits\10\include\10.0.10240.0\ucrt\tchar.h
注意: 包含文件:  C:\Program Files (x86)\Windows Kits\8.1\include\um\tpcshrd.h
f:\base_mbbill\chromium_base\src\base\win\win_util.cc(26): fatal error C1083: 无法打开包括文件: “uiviewsettingsinterop.h”: No such file or directory
ninja: build stopped: subcommand failed.

**Comment by mbbill** [comment]
The header is a part of the WinSDK. Make sure you have win10 sdk installed.
